import "./globals.css";
import { Archivo } from "next/font/google";
import Sidebar from "@/components/layout/Sidebar/Sidebar";
import Footer from "@/components/layout/Footer/Footer";

const archivo = Archivo({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-archivo",
  display: "swap",
});

export const metadata = {
  title: "JewelLabel - Home",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "#ffffff",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="minimal-ui" />
      </head>
      <body className={`${archivo.variable} antialiased bg-white`}>
        <div
          role="outer-wrapper"
          className="min-h-screen grid md:grid-cols-[80px_1fr] grid-cols-1 grid-rows-[60px_1fr] md:grid-rows-1"
        >
          <div
            className="col-span-1 md:row-span-2 md:sticky md:top-0 z-[999]"
            suppressHydrationWarning
          >
            <Sidebar />
          </div>
          <main
            role="inner-wrapper"
            className="flex flex-col flex-nowrap gap-[50px] md:gap-[130px] w-full  min-w-0"
          >
            {children}
            <Footer />
          </main>
        </div>
      </body>
    </html>
  );
}
